### ISSUE TITLE
[support] Include Xposed classes in framework

### ISSUE THREAD

**Issue by etmatrix** [CalebFenton/simplify#100]
I trying to simplify the same apk from issue #99 but I have a issue, this apk use Xposed framework which in not included in apk but is referenced in external not standard android framework.
How can I add it to simplify?
If I run simplify on all apk's classes I got NoClassDefError for Xposed class.

**Comment by CalebFenton** [comment]
First, you'll need to get those Xposed classes. I'm not sure the best way to do that. Maybe they're all easy to see in the Xposed installer.

The easiest thing to do may be to compile your apk's dex file with those classes. (Baksmali the apk, baksmali Xposed, combine smali files, build new dex file). There might be a risk of hitting the 65535 limit for methods.

Another thing you could do is get the smali files for the xposed classes, add them to `smalivm/src/main/resources/framework/smali` and then run [FrameworkJarBuilder](https://github.com/CalebFenton/simplify/blob/master/smalivm/src/main/java/org/cf/smalivm/dex/FrameworkJarBuilder.java) to update the framework jar and the list of framework classes.

**Comment by hrkfdn** [comment]
I am currently messing with this as well, because I'd like to dynamically extract all hooks. Here's what worked to get Xposed integrated:
- Adding XposedBridge to the framework
- Running baksmali on the target .dex and the XposedBridge.dex

Interestingly, it would usually kill the JVM in libz in most cases:
```
Stack: [0x00007eff74bfc000,0x00007eff74cfd000],  sp=0x00007eff74cfb740,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libz.so.1+0xc2b8]  inflateEnd+0x18
j  java.util.zip.Inflater.end(J)V+0
j  java.util.zip.Inflater.end()V+29
j  java.util.zip.Inflater.finalize()V+1
J 1072 C1 java.lang.ref.Finalizer.runFinalizer(Lsun/misc/JavaLangAccess;)V (62 bytes) @ 0x00007eff753a0084 [0x00007eff7539fb00+0x584]
J 1071 C1 java.lang.ref.Finalizer.access$100(Ljava/lang/ref/Finalizer;Lsun/misc/JavaLangAccess;)V (6 bytes) @ 0x00007eff7539e29c [0x00007eff7539e240+0x5c]
j  java.lang.ref.Finalizer$FinalizerThread.run()V+45
v  ~StubRoutines::call_stub
V  [libjvm.so+0x67d13b]
V  [libjvm.so+0x67a7fb]
V  [libjvm.so+0x67ade7]
V  [libjvm.so+0x6c0c0b]
V  [libjvm.so+0xa47d73]
V  [libjvm.so+0xa481a2]
V  [libjvm.so+0x8e3002]
C  [libpthread.so.0+0x75aa]  start_thread+0xda

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  java.util.zip.Inflater.end(J)V+0
j  java.util.zip.Inflater.end()V+29
j  java.util.zip.Inflater.finalize()V+1
J 1072 C1 java.lang.ref.Finalizer.runFinalizer(Lsun/misc/JavaLangAccess;)V (62 bytes) @ 0x00007eff753a0084 [0x00007eff7539fb00+0x584]
J 1071 C1 java.lang.ref.Finalizer.access$100(Ljava/lang/ref/Finalizer;Lsun/misc/JavaLangAccess;)V (6 bytes) @ 0x00007eff7539e29c [0x00007eff7539e240+0x5c]
j  java.lang.ref.Finalizer$FinalizerThread.run()V+45
v  ~StubRoutines::call_stub
```

I used GravityBox as sample, which is pretty hefty. It works better with smaller samples.

**Comment by CalebFenton** [comment]
I'd need a lot more detail to try and reproduce the JVM crash. I think it's pretty safe to assume smalivm won't execute the code the way you want it to and if you're having to use xposed, you should probably be executing on an actual dalvik vm. There's too much native stuff, too much file IO, etc. that isn't going to be handled by smalivm.

The idea of allowing for additional libraries / dex files is going to be carried on here: https://github.com/CalebFenton/simplify/issues/100
