### ISSUE TITLE
Constant Propagation

### ISSUE THREAD

**Issue by mehrant95** [CalebFenton/simplify#102]
I was trying to reverse engineer some malicious app to extract a hidden URL and i came to this lines of codes in java source code:

```java
this.c = "1760";
this.d = new String(Base64.decode(Application.a, 0));
this.a.loadUrl(this.d + this.c);
```
Where `Application.a` is simply a `public static String` in another package:
```java
public class Application extends android.app.Application
{
  public static String a = "aHR0cDovL2RhbmlmaWxlLmNvbS9kb3dubG9hZC81MjU3Lw==";
}
```
The equivalent smali codes look like this:
```smali
sget-object v1, Lir/devroid/mahvareandroid/application/Application;->a:Ljava/lang/String;
invoke-static { v1, v3 }, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B
move-result-object v1
```
I ran simplify on this app (after resolving some errors) and checked the output but this part of code was the same. Does simplify handles such obfuscation techniques?

**Comment by CalebFenton** [comment]
It should since `Application.a` is a static. Could you post a file hash and the command you used to execute?

**Comment by mehrant95** [comment]
I used ApkTool to extract smali codes from APK file and then ran this command:
```
java -jar simplify-1.2.0.jar -it 'ir.devroid.mahvareandroid' -et 'android/' "/path/to/smali/folder"
```
Here is the file:
https://koodous.com/apks/6d1300afe266ec6be14f63a8ff168696451c383b9f7e29749787d6f9857ee651

**Comment by CalebFenton** [comment]
I'm unable to reproduce your issue. Here's what I'm running: `java -jar build/libs/simplify.jar -it 'ir/devroid/mahvareandroid/main/a/c;->a' sandbox/mahvareandroid.apk`

Here's a snippet of code which, I'm guessing is what you were quoting, from `Lir/devroid/mahvareandroid/main/a/c;`:

```java
private void a() {
    String str = new String(Base64.decode(Application.a, 0));
    try {
      Intent localIntent = new android/content/Intent;
      StringBuilder localStringBuilder = new java/lang/StringBuilder;
      localStringBuilder.<init>();
      localIntent.<init>("android.intent.action.VIEW", Uri.parse(str + "1760"));
      startActivity(localIntent);
      return;
    }
```

After simplifying, the string is decoded:

```java
private void a() {
    try {
      Intent localIntent = new android/content/Intent;
      localIntent.<init>("android.intent.action.VIEW", Uri.parse("http://danifile.com/download/5257/1760"));
      startActivity(localIntent);
      return;
    }
```

Could you try running with the command I gave to see if you still have the same issue?

**Comment by mehrant95** [comment]
Thanks.
I wanted to extract hidden urls from obfuscated APK as i want to build something to detect bank phishing pages inside malwares. Maybe i'm in the wrong road but i just used this tool for malware analysis. Any recommendation for automatically detecting obfuscated urls inside malwares? (currently testing sandboxes for this purpose)

**Comment by CalebFenton** [comment]
@mehrant95 that use case makes sense, and my assumption about your goals was wrong. Basically, I have limited time and I'd rather help people doing analysis (like you) and not people trying to crack stuff.

You can detect obfuscated strings by collecting strings and measuring entropy -- higher entropy means they're probably obfuscated. This is used in machine-learning stuff for detecting malware and I have a library which might help here https://github.com/CalebFenton/apkfile.

As far as statically detecting obfuscated strings which are URLs, this is pretty difficult. You could see how the string is used. In this case the string is parsed as a Uri, and in other cases it might be used in an Http request, but in general it's not possible. In specific cases, like base64 encoding, you can just collect all strings, check if base64 encoded, decode, look for URL pattern. A lot of malware is packed and/or obfuscated with something better than base64 so this doesn't help you too much.

Dynamic detection is a bit easier, as you can either hook the OS or monitor network traffic when you  execute an app. The hard part is exercising all the right execution paths.
