### ISSUE TITLE
does simplify work on desktop java ?

### ISSUE THREAD

**Issue by beppe9000** [CalebFenton/simplify#103]

**Comment by CalebFenton** [comment]
What? What is desktop java?

**Comment by beppe9000** [comment]
jar files you run on PCs

**Comment by CalebFenton** [comment]
Ahh. Does simplify work on Java bytecode in addition to Dalvik bytecode?

No. It only supports Dalvik ops, though it's _theoretically possible_ to compile the JAR to a DEX and then deobfuscate it.

**Comment by beppe9000** [comment]
Can I pass a DEX file or do I have to make an APK ?

**Comment by CalebFenton** [comment]
Either one.

Be sure and take a few minutes to understand the types of obfuscation simplify deals with, and try and get a handle on how to use it. It's not a point-and-click win button for obfuscation.

Also, whenever you decompile your Java classes to Java source, you're going to probably get invalid Java. Just a heads up.

The best way to use this tool is to be specific about what you want to analyze. If you just throw a whole app into it, you are very unlikely to find success.
