### ISSUE TITLE
使用ApkTool反编译obfuscated-app_simple.apk查看源代码，发现代码并没任何变化 这是什么问题？

### ISSUE THREAD

**Issue by goodluckforme** [CalebFenton/simplify#106]
```
C:\Users\Administrator\Desktop\jiuzaikan\反混淆>java -jar D:\androidSpace\simplify-master\simplify\build\libs\simplify-1.2.0.jar -it 'org/cf/obfuscated' -et 'MainActivity' obfuscated-app.apk
Simplification complete:
        total classes = 0
        total methods = 0
        optimized methods = 0
        failed methods = 0
        run time = 9912 ms
Total optimizations:

Writing output to obfuscated-app_simple.apk
```

**Comment by CalebFenton** [comment]
I can't reproduce your problem -- it works fine for me:
```
$ java -jar build/libs/simplify-1.2.0.jar -it 'org/cf/obfuscated' -et 'MainActivity' obfuscated-app.apk
<... many lines ...>
Simplification complete:
	total classes = 19
	total methods = 1
	optimized methods = 44
	failed methods = 0
	run time = 17012 ms
Total optimizations:
	constantized ifs = 0
	constantized ops = 70
	dead assignments removed = 173
	dead ops removed = 3
	dead results removed = 63
	nops removed = 0
	peephole optmizations = 12
	unreflected fields = 1
	unreflected methods = 2
	useless gotos removed = 0
Writing output to obfuscated-app_simple.apk
```

How did you clone simplify? Did you use `--recursive`?
How did you build the jar? Was it `gradle fatjar`?
What is the file size of simplify-1.2.0.jar? Is it ~70mb?

**Comment by goodluckforme** [comment]
根据你上面提示今天我又重新使用GIT BASH 拉了一遍
smalivm 中的 AndroidFrameworkSmali库也拉取下来了
整个项目编译后：
模块 simplify 大小73.7MB
模块 smalivm 大小 744MB
simplify-1.2.0.jar  有71.3MB
但是执行结果任然如下
`D:\androidSpace\simplify-master_new\simplify>java -jar simplify/build/libs/simplify-1.2.0.jar -it 'org/cf/obfuscated' -et 'MainActivity' simplify/obfuscated-app.apk
Simplification complete:
        total classes = 0
        total methods = 0
        optimized methods = 0
        failed methods = 0
        run time = 5565 ms
Total optimizations:
`

**Comment by CalebFenton** [comment]
Everything looks good, though I have to infer some things based on file sizes.

This is very strange. It makes me think there's a problem with Windows. It looks like it's not finding any classes or it's somehow filtering them all out.

Most importantly, add `-v 2` to your arguments so we can have more info on what's happening.

Try removing the `it` and `et` arguments.
What version of the JDK did you use?

I don't have a Windows machine near by to test this.

**Comment by CalebFenton** [comment]
Cloning is failing because the path is too long. This is a Git and file system issue. I recommend trouble shooting by searching Google or baidu for "Git unable to create file filename too long"

**Comment by Lemniscate317** [comment]
I get this too.
```
Simplification complete:
        total classes = 0
        total methods = 0
        optimized methods = 0
        failed methods = 0
        run time = 3925 ms
Total optimizations:        
```

may be windows have some problem

**Comment by strazzere** [comment]
@Lemniscate317 it's a file system issue as described above. You're trying to have a very long path/file name on a filesystem which won't allow it.

**Comment by CalebFenton** [comment]
+1 to what @strazzere said. The error that comes up over and over again is: `Filename too long`. Try doing everything in a directory closer to your root directory, like `C:\simplify`. This is a limitation of Windows and there's nothing I can do.

If `git` is throwing errors, [either](https://en.wikipedia.org/wiki/Occam%27s_razor) 1.) you found a problem in git or 2.) there's something odd about your environment.

**Comment by GSharma789** [comment]
Anyone please upload this demo apk which you guys are trying to deobfuscate ,i think thhis org/cf/obfuscated one is that included in simplify demo source but  i don't have android studio or gradle or anything that can build. Thanks in advance
