### ISSUE TITLE
performance, SmaliClassLoader.loadClass()

### ISSUE THREAD

**Issue by ehsmeng** [CalebFenton/simplify#113]
Hi, 
Is the following performance optimization ok, or am I missing something crucial here?
Thanks!

[smalivm.diff.txt](https://github.com/CalebFenton/simplify/files/2437412/smalivm.diff.txt)
![before](https://user-images.githubusercontent.com/908449/46342636-346d2500-c633-11e8-8739-447b6d239d43.png)
![after](https://user-images.githubusercontent.com/908449/46342639-3636e880-c633-11e8-930a-7d2c5711b322.png)

**Comment by CalebFenton** [comment]
Ahh yeah, neither `ClassManager.getFrameworkClassNames()` nor `ClassManager.getNonFrameworkClassNames()` cache the results of filtering the keys. This is certainly something that could be changed. I think a better place to cache this is in `ClassManager` so any callers of that method could benefit from the cache, and also might as well cache `getNoneFrameworkClassNames`.

I'm curious though -- if you're profiling the code, it's true that a lot of the initial work is done loading classes and getting the VM initialized, but in my experience, this load becomes completely trivial after the execution starts. Have you profiled execution of any non-trivial methods? Or are you just calling this method a lot in your particular use case? If so, could you explain your use case a bit? -- I'm curious.

**Comment by CalebFenton** [comment]
I'm going to close this since I've adapted the change, but I'm still curious about my questions above.
