### ISSUE TITLE
Why is the encrypted string in the StringHolder class in the demo not resolved?

### ISSUE THREAD

**Issue by ihbing** [CalebFenton/simplify#125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DXCyber409** [comment]
Complile in linux, not in windows.

**Comment by ihbing** [comment]
Sorry, I got it wrong. The StringHolder class in the demo is optimized.

**Comment by ihbing** [comment]
This tool is really powerful

**Comment by CalebFenton** [comment]
Thanks for the feedback. 👍🏼
