### ISSUE TITLE
Unable to deobfuscate using simplify

### ISSUE THREAD

**Issue by AzrhadiBW** [CalebFenton/simplify#131]
Iam unsure why all the values are 0.

![sim](https://user-images.githubusercontent.com/26666074/64711736-b248da00-d4ec-11e9-8807-f87704bec873.PNG)

**Comment by AzrhadiBW** [comment]
Upon using the command i did get a generated apk file. However after trying to deobfuscate it, white noise class remained obfuscated.

**Comment by CalebFenton** [comment]
Looks like no classes were executed. Can you run again with `-v`?

**Comment by strazzere** [comment]
$10 says your baksmali failed to extract the classes on Windows due to the filesystem path length issues.

**Comment by AzrhadiBW** [comment]
Is ./gradle fatjar suppose to create the directory "simplfy/build/libs/simplaify.jar"?

**Comment by AzrhadiBW** [comment]
![cal](https://user-images.githubusercontent.com/26666074/64719428-d01d3b80-d4fa-11e9-8314-9344402d9702.PNG

Use -v like this?

**Comment by CalebFenton** [comment]
No, gradle fatjar is not supposed to create a directory named simplify.jar. It should create a file in approximately that location.

No, don't use -v like that, as you might could gather by the error. With command line interfaces, it's pretty common to use -h for help and -v for verbose. So try -h and it'll tell you how to best use -v. In this case, `-v 1` is probably enough.

Also, @strazzere makes a good suggestion. To test this, try running simplify from `c:\` or try using baksmali from that current directory.

**Comment by CalebFenton** [comment]
Closing because it's a problem with your environment. Feel free to continue discussion here.
