### ISSUE TITLE
Obfuscated with symbols naming

### ISSUE THREAD

**Issue by lyndmi** [CalebFenton/simplify#135]
**Provide specific APK, DEX, or file hash**
[lp.zip](https://github.com/CalebFenton/simplify/files/4103462/lp.zip)

**Describe the bug**
Failing to deobfuscate. maybe because of weird symbols that the program can't read? the porgram read them as questionmarks

Log: https://pastebin.com/Gi2nThtP

If you decompile with apktool. you see folders with weird names

**To Reproduce**
`java -jar simplify-1.2.1.jar "soruce.apk" -ie -o "out.apk" --max-address-visits 10000 --max-call-depth 10000 --max-method-visits 10000`

**Attempted work-arounds**
I'm not familar with regex so can't use `-it`
I used `--max-address-visits, --max-call-depth, and --max-method-visits`
And `-v`

**Screenshots**
No applicable.

**Additional context**
None

**Comment by CalebFenton** [comment]
Thanks for using the template!

I suspect the question marks are a problem with the console you're using. Is it Windows?

You don't have to know regex. You really just need to know method signatures. What methods or classes do you care about?

**Comment by CalebFenton** [comment]
The question marks seem to be an artifact of your environment, probably Windows. I can't reproduce.

I need to make the documentation more clear that simplify isn't a point-and-click solve-all-your-problems too. It's made for reverse engineers and malware analysts that know what they're doing and need to deobfuscate code. It's not really for people who just want to rename classes so it's easier to steal code from a commercial app.

Feel free to reopen if you think this is malware or if you have a specific class or method you want to deobfuscate but it's failing.
