### ISSUE TITLE
How can I deobfuscation a jar file?

### ISSUE THREAD

**Issue by xpy051** [CalebFenton/simplify#138]
Hello, 
I have a jar file that is confused by Android studio, but I don't know how to use this tools to deobfuscate。

**Comment by CalebFenton** [comment]
![](https://media.giphy.com/media/glmRyiSI3v5E4/giphy-downsized-large.gif)

**Comment by CalebFenton** [comment]
Read the documentation and google terms you don't understand. Let me know if you have any bugs.
