### ISSUE TITLE
The obfuscated-app.apk de-obfuscation failed with simplify-1.3.0.jar

### ISSUE THREAD

**Issue by ihbing** [CalebFenton/simplify#158]
![image](https://user-images.githubusercontent.com/27600008/107340607-eddc3f00-6af8-11eb-917d-7567cf9100d2.png)
![image](https://user-images.githubusercontent.com/27600008/107341093-87a3ec00-6af9-11eb-89b2-df0588399ffc.png)

[simplify-1.3.0.jar](https://github.com/CalebFenton/simplify/releases/tag/v1.3.0)

[obfuscated-app.apk](https://github.com/CalebFenton/simplify/files/5950131/obfuscated-app.apk.zip)

win 10 2004

**Comment by apkunpacker** [comment]
use double quotes " " instead of single in commands . windows not working well with ' '

**Comment by CalebFenton** [comment]
Thanks for handling this @apkunpacker. I'm tempted to not update the readme to torture windows users. To be fair, you want to use single quotes for a regex in bash because it might have odd characters.

**Comment by CalebFenton** [comment]
https://github.com/CalebFenton/simplify/commit/34ee483d498f3afa5670350365e183f207b6eaca
