### ISSUE TITLE
onBind default code should not raise a IllegalStateException that kills execution

### ISSUE THREAD

**Issue by strazzere** [CalebFenton/simplify#34]
IllegalStateException occurs when parsing default onBind methods from Android Services - unsure if it's specific to anything around that, I haven't been able to debug it at all. Just dropping this here so one of us can pick it up later.

>Executing: Lcom/some/classfrommalware;->onBind(Landroid/content/Intent;)Landroid/os/IBinder;
>Simplifying: Lcom/some/classfrommalware;->onBind(Landroid/content/Intent;)Landroid/os/IBinder;
>Exception in thread "main" java.lang.IllegalStateException: Cannot get the location of an instruction that >hasn't been added to a method.
>	at org.jf.dexlib2.builder.BuilderInstruction.getLocation(BuilderInstruction.java:65)
>	at org.cf.smalivm.context.ExecutionGraph.buildAddressToNodePile(ExecutionGraph.java:40)
>	at org.cf.smalivm.context.ExecutionGraph.<init>(ExecutionGraph.java:100)
>	at org.cf.smalivm.VirtualMachine.updateInstructionGraph(VirtualMachine.java:204)
>	at org.cf.simplify.Main.main(Main.java:71)

Sample smali code that will hit this;
```
.class public Lcom/some/classfrommalware;
.super Landroid/app/Service;
.source "Diff.java"

# ... snip ...

.method public onBind(Landroid/content/Intent;)Landroid/os/IBinder;
    .registers 3
    .param p1, "intent"    # Landroid/content/Intent;

    .prologue
    .line 70
    const/4 v0, 0x0

    return-object v0
.end method

#... snip ...
```

**Comment by CalebFenton** [comment]
This error is consistent with building against dexlib-2.0.3. You gotta remove 2.0.3 from your class path manually because `./gradlew cleanEclipse` doesn't seem to do it, then fix the build.gradle. This has bitten me multiple, multiple times.

**Comment by strazzere** [comment]
Odd I was almost positive I corrected that because I figured it was the issue - I'll nuke my environment and retry tomorrow.

**Comment by CalebFenton** [comment]
I've had both dexlib 2.0.3 and 2.0.3-dev in my build path and it just happened to pick 2.0.3 first. This might be something new, but I've only ever seen it because of this bug: https://github.com/JesusFreke/smali/commit/d354893f713957bfc8080798aed9c12c640ac51d

**Comment by strazzere** [comment]
FML it was exactly this bug. For some reason I assumed doing;
```
./gradlew clean cleanEclipse shadow eclipse
```

Would clear my gradle caches, which it did not -- I ended up needing to just remove that caches jar all together from my users environment to be sure;

```
rm -rf ~/.gradle/caches/modules-2/files-2.1/org.smali/dexlib2/2.0.3/
```
