### ISSUE TITLE
MethodExecutor and MethodOP Object into String error

### ISSUE THREAD

**Issue by Disane** [CalebFenton/simplify#39]
I got a new sample where I merely want to reveal a couple of strings. Unfortunately, the MethodExecutor and MethodOP runs into a problem where it tries to cast an Object into a String. See www.pastebin.com/dFhhzftE

The sample's SHA1 can be found @ www.pastebin.com/11pNMG45 
It is the newest Triada Backdoor for Android OS, this version obfuscates the strings in its functions that interact with the system's shell and executes various tasks. I tried to run simplify over the smali code that I got from the sample using APKTool 2.0.1 and pass the parameter -it "t;->a"

I thought it might be a nice candidate for testing Simplify unfortunately I got errors :-/ (as mentioned above).  If you have no access to the sample, then please let me know and I'll send it to you. (I just can't do it now, because I'm writing this e-mail on my tablet computer).

What I want to achive is to reveal the obfuscated strings that are passed as parameter to exec(). Who knows? Maybe I'm just using Simplify wrongly.

Could you please help with this?

Thanks a lot in advance!

The pastebin links will be available for two weeks and the sample is also available on virustotal.

**Comment by CalebFenton** [comment]
I believe you're using the 0.8 release and not the latest build from source. Even still, I'm able to reproduce this or a similar issue.

**Comment by CalebFenton** [comment]
Thanks for the error report :D
