### ISSUE TITLE
Problem with building question

### ISSUE THREAD

**Issue by ShoubhikRaj** [CalebFenton/simplify#41]
When I try to build the project using >gradle build I get the error "Execution failed for task ':smalivm:compileJava:'. >invalid source release : 1.8". Am I doing something wrong?
I am using gradle 2.10. If I try to build it with >gradlew fatjar it starts downloading gradle 2.7.
Thank you for any help.

**Comment by CalebFenton** [comment]
I believe "invalid source release" is from not using Java 8. Could you run `java -version` and make sure it's 8? Try to build again with java 8 and let me know if you still have any issues.

Sorry about the Java 8 requirement. I really wanted to play around with all the new features.

**Comment by CalebFenton** [comment]
In the interest of making myself feel better by having fewer open issues and because I'm 99% sure that my suggestion gets to the very meaty heart of your issue, I'm closing this. Feel free to re-open with a snarky attitude if you still have issues.

**Comment by ShoubhikRaj** [comment]
Using Java 8 indeed solves the problem. Thank you
