### ISSUE TITLE
Cause the error of the DEX file need help.

### ISSUE THREAD

**Issue by jackeyprince** [CalebFenton/simplify#51]
@CalebFenton  i can upload dex file 
[errorclasses.zip](https://github.com/CalebFenton/simplify/files/383132/errorclasses.zip)

**Comment by CalebFenton** [comment]
Didn't realize you could attach files.

Could you tell me what command you used to execute the program? Specifically, which classes and methods were you trying to execute?

**Comment by CalebFenton** [comment]
Feel free to re-open if you ever want to explain where the error is.
