### ISSUE TITLE
java.lang.RuntimeException: Error loading class defin > ition: Landroid/icu/text/MessagePatternUtil

### ISSUE THREAD

**Issue by Jasi2169** [CalebFenton/simplify#54]
> > C:\Users\JASI\Desktop\Android\classes\Source>java -jar C:\Users\JASI\Desktop\And
> > roid\classes\simplify-1.1.0.jar -it 'o' C:\Users\JASI\Desktop\Android\classes\So
> > urce
> > Simplified 0 methods from 0 classes in 32472 ms.
> > Total optimizations:
> 
> Writing output to Source_simple.dex
> 
> C:\Users\JASI\Desktop\Android\classes\Source>java -jar C:\Users\JASI\Desktop\And
> roid\classes\simplify-1.1.0.jar -it 'com/actionlauncher' C:\Users\JASI\Desktop\A
> ndroid\classes\Source
> Simplified 0 methods from 0 classes in 20601 ms.
> Total optimizations:
> 
> Writing output to Source_simple.dex
> 
> C:\Users\JASI\Desktop\Android\classes\Source>java -jar C:\Users\JASI\Desktop\And
> roid\classes\simplify-1.1.0.jar C:\Users\JASI\Desktop\Android\classes\Source
> Executing: Lcom/android/launcher3/AlphaDisableableButton;-><init>(Landroid/conte
> nt/Context;Landroid/util/AttributeSet;)V
> Exception in thread "main" java.lang.RuntimeException: Error loading class defin
> ition: Landroid/icu/text/MessagePatternUtil;
>         at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:161)
>         at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.j
> ava:179)
>         at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:117
> )
>         at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:132
> )
>         at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:11
> 0)
>         at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:7
> 8)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
>         at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:
> 40)
>         at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:19
> 6)
>         at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:18
> 6)
>         at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:87)
>         at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
>         at org.cf.simplify.Launcher.run(Launcher.java:153)
>         at org.cf.simplify.Main.main(Main.java:14)
> Caused by: java.lang.NullPointerException
>         at java.io.Reader.<init>(Unknown Source)
>         at java.io.InputStreamReader.<init>(Unknown Source)
>         at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
>         at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:158)
>         ... 15 more
> 
> C:\Users\JASI\Desktop\Android\classes\Source>

the target is commercial and protected with dexguard 7 enterprise
Action Launcher 3 https://play.google.com/store/apps/details?id=com.actionlauncher.playstore&hl=en

when i try to limit nothing is simplified so i tried loading all source well classes.dex is almost 6mb

**Comment by CalebFenton** [comment]
Could you try again with latest commits? Many changes have been made to class generation.

**Comment by Jasi2169** [comment]
tried 
1. if i try full to source /smali then same runtimeexception

if i use some classes or some packages inside main package the output will be showing

> 
> Simplified 0 methods from 0 classes
> Total optimizations:
> 
> Writing output to smali_simple.dex
