### ISSUE TITLE
[Q] does simplify support multi-dex?

### ISSUE THREAD

**Issue by Lanchon** [CalebFenton/simplify#60]

**Comment by CalebFenton** [comment]
I haven't tried; probably not. Do you have an APK? It would save me having to make one.

**Comment by Lanchon** [comment]
any app can be converted to multi-dex using DexPatcher. here is one such app under a free license:
https://github.com/DexPatcher/dexpatcher-gradle-samples/tree/master/multi-dex/source/apk

if you haven't explicitly coded multi-dex, then simplify does not support it. i've made [multidexlib2](https://github.com/DexPatcher/dexpatcher-tool/tree/v1.2.0/tool/src/main/java/lanchon/multidexlib2), a wrapper over dexlib2 that supports multi-dex. you can read a few bulletpoints about it [here towards the end](https://github.com/DexPatcher/dexpatcher-tool/releases/tag/v1.2.0).

important for you is: "_Simplified read/write access to multi-dex containers as plain-old dexlib2 DexFile objects, making it trivial to add multi-dex support to existing non-multi-dex-aware dexlib2 clients._". just replace the DEX file read and write calls into dexlib2 with the multidexlib2 variants and you are mostly done. the classes to look into are `MultiDexIO` and maybe `RawDexIO` if you need it.

the problem is the license: it is GPLv3 or later, while you want to commercially dual license license your code.

**Comment by CalebFenton** [comment]
Thanks for bringing your tool and library to my attention. As you point out, I won't be able to actually use it for simplify, but I may use it for other projects.

As far as implementing multi-dex in simplify, it would be nice but it's probably an edge case. Simplify is meant to work on offensive samples which are usually single dex. If they're multi-dex, it's possible to operate on each dex individually. It should be possible to hack additional "reference" dex files in so if code in the input dex file references code in the other dex, it could load and execute it. But each file would be emulated and written individually. This flexibility to supply reference dex'es may be preferable to transparent multi-dex handling in some cases.

**Comment by Lanchon** [comment]
simplify can be used as a general deobfuscator and as such it is applicable to non-malicious code, hence multidex enters the picture. individual dex processing is not a good idea IMHO, because ART treats multidex as single unit and so there is no advantage. also when processing individual dex parts, although you can certainly read each dex, writing the processed version of the dex can fail due to a pool overflow. dex breakup should be at the last stage of processing.

anyway, the good news is that we can fork simplify if needed, thanks for this awesome tool btw!!

**Comment by CalebFenton** [comment]
Closing this since it's outside the scope of simplify (dex parsing is hard) and there's a ghetto work-around (dump all dex's to a single directory and work on that)

**Comment by Osipion** [comment]
@CalebFenton - could you provide an example of this "ghetto work-around"? Say I have a multi-dexed `apk`, which, when unzipped, has 2 `.dex` files - `classes.dex` and `classes2.dex`. Code in `classes.dex` depends on code defined in `classes2.dex`, so currently `simplify` throws an error complaining the the class referenced by `classes.dex` (which exists in `classes2.dex`) couldn't be found.  `apktool` converts both `.dex` files to smali (e.g. creates `smali/` and `smali_classes2/` directories). Whats the appropriate want to combine these `dex` files or `smali` directories so I can use `simplify` effectively?

**Comment by CalebFenton** [comment]
Most of the time, the overwhelming majority of classes and methods are in
uninteresting advertising libraries. Knowing this, just combine all smali
directories, delete the ad libraries, and compile what's left into a single
Dex.

You should probably be doing a bit of recon before using simplify, so you
should have a good idea which packages are unrelated.

This approach also works for dynamically unpacked Dex payloads as well.

**Comment by Osipion** [comment]
Ah, that makes sense. Delete all libs that aren't dependencies of the classes I want to analyze, move the remaining directories under `smali`, and rebuild to a single dex file.

**Comment by CalebFenton** [comment]
You got it. Good luck. 👍🏼
