### ISSUE TITLE
SmokeTest Error - Error loading Class Definition  

### ISSUE THREAD

**Issue by deadeert** [CalebFenton/simplify#71]
Hi here,

I successfully build the package using `java-8-oracle` version.
`java -version`
>java version "1.8.0_66"
>Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
>Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

When I perform the demo test you provide on your READ.MD the following error (I provide the stack trace) : 
`java -jar simplify/build/libs/simplify.jar -it 'org/cf' simplify/obfuscated-example`

>
> class manager with this path: /obfuscated-example
>Executing: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
>Exception in thread "main" java.lang.RuntimeException: Error loading class definition: Landroid/icu
>/text/MessagePatternUtil;
>	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:169)
>	at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:188)
>	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:121)
>	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:140)
>	at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:114)
>	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:92)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>	at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
>	at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:39)
>	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:173)
>	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:164)
>	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:62)
>	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
>	at org.cf.simplify.Launcher.run(Launcher.java:153)
>	at org.cf.simplify.Main.main(Main.java:14)
>Caused by: java.lang.NullPointerException
>	at java.io.Reader.<init>(Reader.java:78)
>	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
>	at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
>	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:166)
	... 15 more

When I try on a different small dex file, I got the same issue. 

Have you any idea of what happen ?

**Comment by CalebFenton** [comment]
Did you clone submodules? It reads like the framework smali files are missing.

**Comment by deadeert** [comment]
You are perfectly right, I forgot the `--recursive` option. :100: 
Sorry about that and thanks for your help, I'm really looking forward testing your tool :]
