### ISSUE TITLE
Progress bar / Estimate of time left

### ISSUE THREAD

**Issue by strazzere** [CalebFenton/simplify#73]
This is likely a pipe dream, however some form of anticipated wait time or progress bar (as simple as processed X of N files) would be interesting as a form of understanding the progression of the simplification.

**Comment by CalebFenton** [comment]
What about, for each top level method that gets executed, it could include something like "Executing XXX (9 of 123)" ? Or do you want a full-blown fancy-pants progress bar?

**Comment by strazzere** [comment]
This would make sense -- honestly anything which might just give an indication of how far the current process has gone and what may be left.
