### ISSUE TITLE
[Windows path_length issue >260 characters] smali filenames are too long

### ISSUE THREAD

**Issue by Disane** [CalebFenton/simplify#81]
Hey Caleb,

I think the smali submodule might be causing problems on windows, as the relative path sizes are just simply too big. Here's one example:

error: unable to create file android-25/java/util/stream/ReferencePipeline$9$1$-void__init__java_util_stream_ReferencePipeline$9_this$1_java_util_stream_Sink_$anonymous0_java_util_function_Function_val$mapper_LambdaImpl0.smali: Filename too long

I'm not sure if this is something you want to fix, but I'll just leave it here for now.

Br,
Disane

**Comment by CalebFenton** [comment]
Thanks for the report. Do you have a file hash you can share?

**Comment by Disane** [comment]
Hey Caleb!

The error occurs when you try to clone the repository from GitHub. It doesn't matter if you use the Desktop Application of GitHub or the command line, both yield the same error. So, there's no hash this time.

I know, it's dumb, but it happens. I'm only mentioning this, cause I remember using simplify and smalivm on Windows before. Back then I think I did not clone the backsmali module, but ran simplify on .smali files.

This repository clones flawlessly on Linux though!

**Comment by CalebFenton** [comment]
It's not dumb. I like having these issues because they're indexed in search engines and might help other people. So, thanks!

That submodule is the reference framework. It's basically a disassembly of Android in Smali. Unfortunately, I don't think there's an easy fix for this. I could compress the framework,, but then simplify would have to uncompress at run time and perhaps cache it somewhere. I don't want to add that complexity / run cost just to support builds on Windows.

Does it work if you clone from c:\simplify or something short?

**Comment by Disane** [comment]
Right, sorry.

I tried C:\simplify, E:\simplify, but no luck. Anyways at least we know what the cause is.

**Comment by ryantheleach** [comment]
Also hitting this bug, going to have to set up a vm.

**Comment by CalebFenton** [comment]
On Windows 10, it may be possible to adjust the max length - https://betanews.com/2016/05/29/long-paths-windows-10/

A proper fix for this might be to intelligently rename long files in the android smali submodule. I'd accept a PR that scripted this into the framework extraction process but I must admit I personally have no interest in bending over backwards to work around an operating system that's hell bent on not being taken seriously.

**Comment by CalebFenton** [comment]
After reviewing this again, I don't think it's worth complicating the code to work-around this. One could just run simplify on *nix or mac in a VM on Windows.
