### ISSUE TITLE
Step 2/8 throws exception during test [This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Can't find Smali file for Lcom/sun/crypto/provider/DESKey;]

### ISSUE THREAD

**Issue by abbana** [CalebFenton/simplify#89]
Hi,

got the error below when trying the test code

[1 / 22] Processing top level class Lorg/cf/obfuscated/Reflection;
(1 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Simplifying: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Optimizations:
	constantized ifs = 0
	constantized ops = 0
	dead assignments removed = 0
	dead ops removed = 0
	dead results removed = 0
	nops removed = 0
	peephole optmizations = 0
	unreflected fields = 0
	unreflected methods = 0
	useless gotos removed = 0
(2 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V
18:30:16.855 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r6, r7, r4}, Ljavax/crypto/Cipher;->init(ILjava/security/Key;)V, @=21} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Can't find Smali file for Lcom/sun/crypto/provider/DESKey;
18:30:16.864 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-static {r7, r13}, Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, @=108} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r2}, Ljava/lang/Throwable;->printStackTrace()V, @=37} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
18:30:16.865 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-static {r3}, Lorg/cf/obfuscated/StringHolder;->get(I)Ljava/lang/String;, @=2} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;-><clinit>()V, op=invoke-static {}, Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, @=112} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-virtual {r5}, Ljava/lang/Throwable;->printStackTrace()V, @=129} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-virtual {r0}, Ljava/lang/Throwable;->printStackTrace()V, @=32} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:185)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)

Seems I am missing some files. Where to get them and where to put them? Al

**Comment by CalebFenton** [comment]
This is the same issue here: https://github.com/CalebFenton/simplify/issues/87

Basically, that class doesn't exist in Android. I'm not sure how this ever worked, and I know it did. I'm also not sure how this app ever compiled, and I know it does. I just haven't looked into it.

Since the class doesn't exist on Android, the demo app should probably be rewritten to use encryption some other way using other classes.

**Comment by abbana** [comment]
Thanks Caleb.

I can see it is similar to #87.

This is my first test and below what done to make it work so far.

git clone --recursive git://github.com/CalebFenton/simplify.git
git clone --recursive git://github.com/CalebFenton/AndroidFrameworkSmali.git

note git with https does not work in suse11 and git submodule update --init --recursive does nohing

cd AndroidFrameworkSmali/
cp -pr android-25 /Obfuscation/de-obfuscator/simplify/smalivm/src/main/resources/framework/smali/
mv  /Obfuscation/de-obfuscator/simplify/smalivm/src/main/resources/framework/smali/android-25 /Obfuscation/de-obfuscator/simplify/smalivm/src/main/resources/framework/smali/android-23
./gradlew fatjar


Meantime you work on the code, can you please provide provide the missing files so I can run and test it?

**Comment by CalebFenton** [comment]
The missing files _literally_ do not exist for Android. I'm not entirely sure how it ever worked. I _suspect_ it had something to do with me dumping a weird device's framework which included Java specific files or that I had something whitelisted for reflection before, but it's not reflected anymore.

Also, you don't need to clone AndroidFrameworkSmali for simplify or smalivm. It's a submodule and will be cloned with `--recursive`. You shouldn't need to move anything.

The instructions in the readme work on mac and several distros of linux. If git is broken on suse11, I think the solution is to upgrade git yourself.

You can test simplify with `gradle test`. It's only the demo app which isn't working right now, and only parts of it.

**Comment by abbana** [comment]
Thanks Caleb,
gradlew test worked as a charm.

I needed to download them manually and move because git with https seems not to work on my system. And doing git --recursive git://url results in first cal with git protocol, next ones with https 

So I felt in #87 and moving them + recompiling solved the problem.

**Comment by strazzere** [comment]
This is interesting -- I was just digging into this on my machine as well and think I understand it a bit more, https://android.googlesource.com/platform/libcore.git/+/51b1b6997fd3f980076b8081f7f1165ccc2a4008

These files _did_ exist at some point, however, they no longer do. I can't genuinely tell when they left AOSP, Androids tagging is kind of insane and it isn't easy to track down.

**Comment by CalebFenton** [comment]
@strazzere THANK YOU. I spent an entire evening digging into #87 and almost lost my damned mind. I figured it couldn't _possibly_ be that they'd remove those classes from the documentation and frameworks because that would break backward compatibility.

I still think the solution should be to rewrite demo app, but at least I don't feel like I'm going senile.

**Comment by strazzere** [comment]
Haha, word - I get the feeling. I saw the error pop up and thought it was weird. Then your reply made me extra interested. This ticket is also the 2nd highest result on Google now.

Future us will be grateful we finally looked into this issue 👯‍♂️

**Comment by abbana** [comment]
@CalebFenton Quick question here: Simplify is running for 12+ hours now. If I hit CRTL+C all the good work done is gone or the changes are committed to the code as soon they are discovered? How the jar works when we set --max-execution-time , it commit the changes or not?

Thanks.

**Comment by abbana** [comment]
@CalebFenton Thanks for that. I was thinking that was the reason. I will let it run for test purposes, hopefully before the winter it will finish!! :-)

One thing I noticed is that --max-execution-time does not work in my ENV, it's just me, or you aware about that?

**Comment by CalebFenton** [comment]
Can you give me an example of it not working? E.g. the file hash and the command you used to execute? It could be that it's getting stuck somewhere. The execution time is checked at some (hopefully) regular point during execution, but it's not monitored by an independent thread, so it can get stuck.

I've also found that 99% of people who use simplify are using it on samples which are only proguarded and have 0 real obfuscation. This is why I think it's beneficial to identify the classes and methods which are important (and _obfuscated_) because if one can't do that, one doesn't need simplify. One probably just needs identifier remapping which can be handled with a text editor's find and replace.

**Comment by abbana** [comment]
@CalebFenton now you telling me that I think I understand what you trying to say. I took --max-execution-time as the maximum time at which simplify can run as a process while I think you are trying to say is related to the execution of a Method. 
Is that correct?

**Comment by CalebFenton** [comment]
I'm pretty sure it's for top level methods.

**Comment by abbana** [comment]
Allright ...

BTW this app has a lot of Identifier and variable remapping plus a lot of noise.  Using dex2jar+procyon and importing it in Android Studio to make a build throws a lot of error for unidentified variable/missed returns and other annoying stuff. Plus the aim is get to know how some code has been build, and hope this tool will help me on that.

To came back to your question, the apk is 30+ MB of striped code. Hopefully before Christmas :-)

**Comment by CalebFenton** [comment]
Without any kind of targeting, it's possible it'll take longer. Or worse, and more likely, it'll crash before it finishes. If you encounter any specific errors, I'll need the hash. Good luck.
